// mockData.js
export const mockApplicationsData = [
    {
      id: 1,
      srNo: 1,
      loanNo: "ATDAM36262",
      crnNo: "K20AE754",
      accountId: "ATDFSLK20AE754",
      approvedDate: "03-07-2025",
      disburseDate: "03-07-2025",
      dueDate: "31-07-2025",
      name: "Kavitha Thanappan",
      currentAddress: "No. 37, 1st cross street, Moorthy nagar, padi,Tiruvallur,Tamil Nadu,600050",
      currentState: "Tamil Nadu",
      currentCity: "Tiruvallur",
      permanentAddress: "No. 37, 1st cross street, Moorthy nagar, padi,Tiruvallur,Tamil Nadu,600050",
      state: "Tamil Nadu",
      city: "Tiruvallur",
      phoneNo: "9884027754",
      email: "kavi.icici@gmail.com",
      password: "3z9a0f",
      appliedAmount: "28000.00",
      approvedAmount: "28000.00",
      adminFee: "3964",
      roi: "0.067",
      tenure: "29",
      renewalSanctionDate: "",
      renewalTenure: "",
      renewalMaturityDate: "",
      renewalOutstandingBalance: "",
      renewalRemarks: "",
      renewalSanctionLetter: "",
      hasPhoto: true,
      hasPanProof: true,
      hasAddressProof: true,
      hasIdProof: true,
      hasSalaryProof: true,
      hasBankStatement: true,
      hasVideoKyc: true,
      approvalNote: "Existing Customer",
      enquirySource: "Desktop",
      hasBankVerificationReport: true,
      hasSocialScoreReport: true,
      hasCibilScoreReport: true,
      hasNachForm: true,
      hasPdc: true,
      hasAgreement: true,
      chequeNo: "Cheque",
      sendToCourier: "No",
      courierPicked: "No",
      originalDocuments: "No",
      receivedDisburse: "Yes",
      behalfOfEmandate: "Behalf of e-mandate",
      loanTerm: "One Time Payment",
      disbursalAccount: "ICICI Bank A/c-5399",
      customerAcVerified: "Yes",
      sanctionLetter: true,
      emandateStatus: "Success 19-05-2023 11:57:39",
      iciciEmandateStatus: "Success",
      readyForApprove: "Ready To Verify",
      bankAcVerification: "Verified",
      disburseApproval: "Approved",
      disburse: "✓",
      collection: "Collection",
      loanStatus: "Disbursed",
      changeStatus: "✎",
      action: "✎",
      remarks: "Remark",
      documentStatus: ".....",
      noc: ".....",
      refundPdc: ".....",
      appraisalReport: "Recommended",
      eligibility: "Eligibility",
      replaceKyc: "",
      settled: "",
      status: "Active",
      createdAt: "2025-07-03T10:30:00Z"
    },
    {
      id: 2,
      srNo: 2,
      loanNo: "ATDAM36263",
      crnNo: "K20AE755",
      accountId: "ATDFSLK20AE755",
      approvedDate: "02-07-2025",
      disburseDate: "02-07-2025",
      dueDate: "30-07-2025",
      name: "Rajesh Kumar",
      currentAddress: "Plot No. 45, Gandhi Nagar, Chennai, Tamil Nadu, 600001",
      currentState: "Tamil Nadu",
      currentCity: "Chennai",
      permanentAddress: "Plot No. 45, Gandhi Nagar, Chennai, Tamil Nadu, 600001",
      state: "Tamil Nadu",
      city: "Chennai",
      phoneNo: "9876543210",
      email: "rajesh.kumar@gmail.com",
      password: "4a8b1c",
      appliedAmount: "50000.00",
      approvedAmount: "45000.00",
      adminFee: "4500",
      roi: "0.085",
      tenure: "24",
      renewalSanctionDate: "",
      renewalTenure: "",
      renewalMaturityDate: "",
      renewalOutstandingBalance: "",
      renewalRemarks: "",
      renewalSanctionLetter: "",
      hasPhoto: true,
      hasPanProof: true,
      hasAddressProof: true,
      hasIdProof: true,
      hasSalaryProof: true,
      hasBankStatement: true,
      hasVideoKyc: true,
      approvalNote: "New Customer",
      enquirySource: "Mobile App",
      hasBankVerificationReport: true,
      hasSocialScoreReport: true,
      hasCibilScoreReport: true,
      hasNachForm: true,
      hasPdc: true,
      hasAgreement: true,
      chequeNo: "Cheque",
      sendToCourier: "Yes",
      courierPicked: "Yes",
      originalDocuments: "Yes",
      receivedDisburse: "Yes",
      behalfOfEmandate: "Behalf of Bank mandate",
      loanTerm: "EMI",
      disbursalAccount: "HDFC Bank A/c-7823",
      customerAcVerified: "Yes",
      sanctionLetter: true,
      emandateStatus: "Success 18-05-2023 14:22:15",
      iciciEmandateStatus: "Success",
      readyForApprove: "Approved",
      bankAcVerification: "Verified",
      disburseApproval: "Approved",
      disburse: "✓",
      collection: "Active",
      loanStatus: "Active",
      changeStatus: "✎",
      action: "✎",
      remarks: "Good Customer",
      documentStatus: "Complete",
      noc: ".....",
      refundPdc: ".....",
      appraisalReport: "Recommended",
      eligibility: "Eligibility",
      replaceKyc: "",
      settled: "",
      status: "Active",
      createdAt: "2025-07-02T09:15:00Z"
    },
    {
      id: 3,
      srNo: 3,
      loanNo: "ATDAM36264",
      crnNo: "K20AE756",
      accountId: "ATDFSLK20AE756",
      approvedDate: "01-07-2025",
      disburseDate: "",
      dueDate: "29-07-2025",
      name: "Priya Sharma",
      currentAddress: "Flat 12B, Sunrise Apartments, Bangalore, Karnataka, 560001",
      currentState: "Karnataka",
      currentCity: "Bangalore",
      permanentAddress: "Flat 12B, Sunrise Apartments, Bangalore, Karnataka, 560001",
      state: "Karnataka",
      city: "Bangalore",
      phoneNo: "9123456789",
      email: "priya.sharma@outlook.com",
      password: "5c2d3e",
      appliedAmount: "75000.00",
      approvedAmount: "70000.00",
      adminFee: "7000",
      roi: "0.095",
      tenure: "36",
      renewalSanctionDate: "",
      renewalTenure: "",
      renewalMaturityDate: "",
      renewalOutstandingBalance: "",
      renewalRemarks: "",
      renewalSanctionLetter: "",
      hasPhoto: true,
      hasPanProof: true,
      hasAddressProof: false,
      hasIdProof: true,
      hasSalaryProof: true,
      hasBankStatement: true,
      hasVideoKyc: false,
      approvalNote: "Pending Documentation",
      enquirySource: "Website",
      hasBankVerificationReport: true,
      hasSocialScoreReport: false,
      hasCibilScoreReport: true,
      hasNachForm: false,
      hasPdc: false,
      hasAgreement: false,
      chequeNo: "Pending",
      sendToCourier: "No",
      courierPicked: "No",
      originalDocuments: "No",
      receivedDisburse: "No",
      behalfOfEmandate: "Pending",
      loanTerm: "EMI",
      disbursalAccount: "SBI Bank A/c-9876",
      customerAcVerified: "Pending",
      sanctionLetter: false,
      emandateStatus: "Pending",
      iciciEmandateStatus: "Pending",
      readyForApprove: "Pending Verification",
      bankAcVerification: "Pending",
      disburseApproval: "Pending",
      disburse: "✗",
      collection: "Pending",
      loanStatus: "Pending",
      changeStatus: "✎",
      action: "✎",
      remarks: "Documents Pending",
      documentStatus: "Incomplete",
      noc: ".....",
      refundPdc: ".....",
      appraisalReport: "Pending",
      eligibility: "Eligibility",
      replaceKyc: "",
      settled: "",
      status: "Pending",
      createdAt: "2025-07-01T16:45:00Z"
    }
  ];